pipeline {
    agent any

    tools {
        maven 'Maven-3' 
    }

    stages {
        stage('Checkout') {
            steps {
                // Récupération du code source depuis GitHub
                checkout scm
            }
        }

        stage('Build & Test') {
            steps {
                dir('devops-app') {
                    // Compilation et exécution des tests unitaires sur Windows
                    bat 'mvn clean test'
                }
            }
        }

        stage('Archive') {
            steps {
                dir('devops-app') {
                    // Génération du JAR et archivage de l'artéfact
                    bat 'mvn package -DskipTests'
                    archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
                }
            }
        }

        stage('Notify Slack') {
            steps {
                // Notification simulée pour valider l'étape de livraison
                echo '✅ Notification : Le pipeline est terminé avec succès.'
            }
        }
    }

    post {
        success {
            echo 'Intégration continue réussie !'
        }
        failure {
            echo 'Échec du pipeline'
        }
    }
}